version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-webserver:
    build: .
    command: webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=very_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-50000}:0"

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=very_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
    user: "${AIRFLOW_UID:-50000}:0"